@extends('layouts.app')
@section('content')
    @include('partials.frontPage.firstSection')
    @include('partials.frontPage.secondSection')
    @include('partials.frontPage.thirdSection')
    @include('partials.frontPage.fourthSection')
    @include('partials.frontPage.fifthSection')
    @include('partials.frontPage.sixthSection')
@endsection